apiVersion: v1
kind: Service
metadata:
  name: data-processor-service
spec:
  selector:
    app: data-processor-service
  ports:
    - name: app
      protocol: TCP
      port: 8082
      targetPort: 8082
    - name: metrics
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP